### ISSUE TITLE
Extract istio gateway conformance tests

### ISSUE THREAD

**Issue by heyste** [apisnoop/gateway-api-test-framework#19]
The Istio conformance tests can be reproduced by running `prow/integ-suite-kind.sh test.integration.pilot.kube` from within the [Istio repo](https://github.com/istio/istio). This process runs the whole integration test suite but we only want to run the conformance tests.

We need to extract the conformance tests and add them to a future `run::istio::conformance` function inside of [implentation/istio.sh](https://github.com/apisnoop/gateway-api-test-framework/blob/main/implementation/istio.sh).

The plan is that any requirements for running conformance tests should be setup as part of  the `deploy::istio` function.

**Comment by BobyMCbobs** [comment]
According to
- https://github.com/istio/istio/blob/381da41/tests/integration/tests.mk#L97-L98
- https://github.com/istio/istio/blob/381da41/tests/integration/tests.mk#L86-L89
- https://github.com/istio/istio/blob/381da41/tests/integration/tests.mk#L7-L81
  - depending on configuration, set any of the flags ub the 2nd `go test` call as `_INTEGRATION_TEST_FLAGS` and `_INTEGRATION_TEST_SELECT_FLAGS`

the commands to run should be something like

```
go test -exec=true -toolexec=./tools/go-compile-without-link -vet=off -tags=integ ./tests/integration/pilot
go test -p 1 ${T} -tags=integ -vet=off -timeout 30m ./tests/integration/pilot ${_INTEGRATION_TEST_FLAGS} ${_INTEGRATION_TEST_SELECT_FLAGS} 2>&1
```

**Comment by BobyMCbobs** [comment]
To run the tests as per CI, it's like

```
docker run -d -p 5000:5000 registry:2
./prow/integ-suite-kind.sh test.integration.pilot.kube
```

seems to be working so far.

**Comment by BobyMCbobs** [comment]
I built the pilot test binary for integration testing with
```
go test -c -v --tags=integ ./tests/integration/pilot/
```

**Comment by BobyMCbobs** [comment]
Brought up a local cluster, same as usual
```
export CONFIG_DIR=${PWD}/config
export IMPLEMENTATION=istio ; ./deploy-kind-gtw-api-cluster.sh
```

With https://github.com/istio/istio/pull/51522, I can build a binary for pilot gateway-api conformance tests with 
```
GOOS=linux go test -c -v --tags=integ ./tests/integration/pilot/gatewayapiconformance/
```

I can build https://github.com/kubernetes-sigs/cloud-provider-kind to run in the VM
```
GOOS=linux go build -o bin/ .
podman machine ssh
./bin/cloud-provider-kind
```

and then run the tests
```
KUBECONFIG=<(kind get kubeconfig) ./gatewayapiconformance.test
```
